"""Tool substrate: ToolResult, Tool base class, ToolContext, dispatch chain.

Every failure is converted into a structured ToolResult (error type +
location + actionable hint) generated by deterministic code — the model
never has to guess what went wrong, and a failing tool never kills the
session.
"""
from __future__ import annotations

import json
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable


@dataclass
class ToolResult:
    ok: bool
    output: str            # fed back to the model; failures carry type + location + hint
    truncated: bool = False


@dataclass
class ToolContext:
    """Shared runtime state handed to every tool call."""

    cwd: Path                                             # persists across bash calls
    default_timeout: float = 120.0                        # bash default (s), capped at 600
    read_files: set[Path] = field(default_factory=set)    # read-before-write contract
    todos: list[dict] = field(default_factory=list)       # todo_write state; read by prompts
    on_file_write: Callable[[Path], None] | None = None   # checkpoint hook (safety layer)


def resolve_path(ctx: ToolContext, path: str) -> Path:
    """Resolve a (possibly relative) tool path against the session cwd."""
    p = Path(path)
    if not p.is_absolute():
        p = ctx.cwd / p
    return p.resolve()


class Tool(ABC):
    name: str
    description: str      # prompt engineering: when to use / not use, examples, failure contract
    parameters: dict      # JSON Schema

    @abstractmethod
    def run(self, args: dict, ctx: ToolContext) -> ToolResult: ...

    def schema(self) -> dict:
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": self.parameters,
            },
        }


class ToolError(Exception):
    """Expected tool failure; dispatch converts it into a structured ToolResult."""


def _try_parse_args(raw: str) -> tuple[dict | None, str | None]:
    """Return (args, error). Tolerates common model slips before giving up."""
    text = raw.strip()
    if not text:
        return {}, None
    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        repaired = re.sub(r",(\s*[}\]])", r"\1", text)  # trailing commas
        try:
            parsed = json.loads(repaired)
        except json.JSONDecodeError as exc:
            return None, f"invalid JSON: {exc.msg} at line {exc.lineno} col {exc.colno}"
    if not isinstance(parsed, dict):
        return None, f"arguments must be a JSON object, got {type(parsed).__name__}"
    return parsed, None


_TYPE_CHECKS = {
    "string": lambda v: isinstance(v, str),
    "integer": lambda v: isinstance(v, int) and not isinstance(v, bool),
    "number": lambda v: isinstance(v, (int, float)) and not isinstance(v, bool),
    "boolean": lambda v: isinstance(v, bool),
    "array": lambda v: isinstance(v, list),
    "object": lambda v: isinstance(v, dict),
}


def _validate_args(args: dict, schema: dict) -> list[str]:
    """Minimal JSON-schema check: required keys + declared primitive types.

    Extra undeclared parameters are tolerated rather than failing the call.
    """
    problems: list[str] = []
    properties = schema.get("properties", {})
    for key in schema.get("required", []):
        if key not in args:
            problems.append(f"missing required parameter {key!r}")
    for key, value in args.items():
        spec = properties.get(key)
        if spec is None:
            continue
        check = _TYPE_CHECKS.get(spec.get("type"))
        if check and not check(value):
            problems.append(
                f"parameter {key!r} must be {spec['type']}, got {type(value).__name__}"
            )
    return problems


def dispatch(registry: dict[str, Tool], name: str, args_json: str, ctx: ToolContext) -> ToolResult:
    """Fault-tolerance chain: json repair → schema check → run → structured
    error feedback. Never raises — the session must survive any tool failure.
    """
    tool = registry.get(name)
    if tool is None:
        return ToolResult(
            False,
            f"error=unknown_tool: no tool named {name!r}. "
            f"Available: {', '.join(sorted(registry))}",
        )
    args, error = _try_parse_args(args_json)
    if error is not None:
        return ToolResult(
            False,
            f"error=bad_arguments: {error}. Fix the JSON and call {name} again.",
        )
    problems = _validate_args(args, tool.parameters)
    if problems:
        return ToolResult(False, f"error=bad_arguments: {'; '.join(problems)}")
    try:
        return tool.run(args, ctx)
    except ToolError as exc:
        return ToolResult(False, f"error=tool: {exc}")
    except Exception as exc:  # unexpected — still never kill the session
        return ToolResult(False, f"error=internal: {type(exc).__name__}: {exc}")
